params:
  seed: 42

  # environment wrapper clipping
  env:
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [1024, 512, 256]
      activation: elu
      initializer:
        name: default
      regularizer:
        name: None #'l2_regularizer'
        #scale: 0.001

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

          
  config:
    name: grasp_lego_v3
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: False
    normalize_value: True
    value_bootstrap: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.02
    score_to_win: 100000
    max_epochs: 100000
    save_best_after: 200
    save_frequency: 1000
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 8
    minibatch_size: 2048
    mini_epochs: 5
    critic_coef: 1
    clip_value: True
    seq_length: 4
    bounds_loss_coef: 0.001

    games_to_track: 8

    player:
      #render: True
      deterministic: True
      max_steps: 100000000
      games_num: 100000000
      print_stats: False
      
    central_value_config:
      minibatch_size: 2048

      mini_epochs: 5
      learning_rate: 1e-3
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.02
      clip_value: True
      normalize_input: True
      truncate_grads: True

      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [1024, 512, 256]
          activation: elu
          d2rl: False
          initializer:
            name: default
          regularizer:
            name: None
