# Copyright (c) 2022-2024, The PsiRobot Project Developers
# Author: Feng Yunduo
# Date: 2025-08-13
# Vesion: 1.0

"""
This file contains the settings for the robot analysis.
"""

import os
from psilab import PSILAB_USD_ASSET_DIR


PSILAB_PATH = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
"""Path to the root directory of the Isaac Lab repository."""

ROBOT_CONFIG = {
    # Psi-AWH-01
    "Psi-AWH-01-Flattened":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_Psi_AWH_01/PsiRobot_AWH_01_Left_Flattened.usd",
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                "joint_rev_link1": 0.0,
                "joint_rev_link2": 0.0,
                "joint_rev_link3": 0.0,
                "joint_rev_link4": 0.0,
                "joint_rev_link5": 0.0,
                "joint_rev_link6": 0.0,
                "joint_rev_link7": 0.0,
                "hand1_joint_link_1_1":0.0,
                "hand1_joint_link_2_1":3.10,
                "hand1_joint_link_3_1":3.06,
                "hand1_joint_link_4_1":3.07,
                "hand1_joint_link_5_1":3.04,
                "hand1_joint_link_1_2":0.63,
                "hand1_joint_link_2_2":1.56,
                "hand1_joint_link_3_2":1.56,
                "hand1_joint_link_4_2":1.56,
                "hand1_joint_link_5_2":1.56,
                "hand1_joint_link_1_3":0.03,
            }
        },
        "actuators":{
            "arm":{
                "joint_names_expr":[
                    "joint_rev_link1",
                    "joint_rev_link2",
                    "joint_rev_link3",
                    "joint_rev_link4",
                    "joint_rev_link5",
                    "joint_rev_link6",
                    "joint_rev_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand":{
                "joint_names_expr":[
                    "hand1_joint_link_1_1",
                    "hand1_joint_link_2_1",
                    "hand1_joint_link_3_1",
                    "hand1_joint_link_4_1",
                    "hand1_joint_link_5_1",
                    "hand1_joint_link_1_2",
                    "hand1_joint_link_2_2",
                    "hand1_joint_link_3_2",
                    "hand1_joint_link_4_2",
                    "hand1_joint_link_5_2",
                    "hand1_joint_link_1_3",
                ],
                "stiffness":None,
                "damping":None,
            }
        },
        "amplitude_scale":1.0,
        "period":10.0,
        "sim_time":20.0,
        "mimic_joints":[
            "hand1_joint_link_2_2",
            "hand1_joint_link_3_2",
            "hand1_joint_link_4_2",
            "hand1_joint_link_5_2",
            "hand1_joint_link_1_3",
        ]
    },
    # Psi-DC-01
    "Psi-DC-01":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_Psi_DC_01/PsiRobot_DC_01.usd",
            "articulation_props":{
                "enabled_self_collisions":False,
            },
            "rigid_props":{
                "solver_position_iteration_count":255,
            }
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                "arm1_joint_link1": 0.0,
                "arm1_joint_link2": 0.0,
                "arm1_joint_link3": 0.0,
                "arm1_joint_link4": 0.0,
                "arm1_joint_link5": 0.0,
                "arm1_joint_link6": 0.0,
                "arm1_joint_link7": 0.0,
                "arm2_joint_link1": 0.0,
                "arm2_joint_link2": 0.0,
                "arm2_joint_link3": 0.0,
                "arm2_joint_link4": 0.0,
                "arm2_joint_link5": 0.0,
                "arm2_joint_link6": 0.0,
                "arm2_joint_link7": 0.0,
                "hand1_joint_link_1_1":0.0,
                "hand1_joint_link_1_2":0.63,
                "hand1_joint_link_1_3":0.03,
                "hand1_joint_link_2_1":3.10,
                "hand1_joint_link_2_2":1.56,
                "hand1_joint_link_3_1":3.06,
                "hand1_joint_link_3_2":1.56,
                "hand1_joint_link_4_1":3.06,
                "hand1_joint_link_4_2":1.56,
                "hand1_joint_link_5_1":3.04,
                "hand1_joint_link_5_2":1.56,
                "hand2_joint_link_1_1":0.0,
                "hand2_joint_link_1_2":0.64,
                "hand2_joint_link_1_3":0.03,
                "hand2_joint_link_2_1":3.11,
                "hand2_joint_link_2_2":1.56,
                "hand2_joint_link_3_1":3.06,
                "hand2_joint_link_3_2":1.56,
                "hand2_joint_link_4_1":3.08,
                "hand2_joint_link_4_2":1.56,
                "hand2_joint_link_5_1":3.05,
                "hand2_joint_link_5_2":1.56,
            }
        },
        "actuators":{
            "arm1":{
                "joint_names_expr":[
                    "arm1_joint_link1",
                    "arm1_joint_link2",
                    "arm1_joint_link3",
                    "arm1_joint_link4",
                    "arm1_joint_link5",
                    "arm1_joint_link6",
                    "arm1_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm2":{
                "joint_names_expr":[
                    "arm2_joint_link1",
                    "arm2_joint_link2",
                    "arm2_joint_link3",
                    "arm2_joint_link4",
                    "arm2_joint_link5",
                    "arm2_joint_link6",
                    "arm2_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand1":{
                "joint_names_expr":[
                    "hand1_joint_link_1_1",
                    "hand1_joint_link_2_1",
                    "hand1_joint_link_3_1",
                    "hand1_joint_link_4_1",
                    "hand1_joint_link_5_1",
                    "hand1_joint_link_1_2",
                    "hand1_joint_link_2_2",
                    "hand1_joint_link_3_2",
                    "hand1_joint_link_4_2",
                    "hand1_joint_link_5_2",
                    "hand1_joint_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand2":{
                "joint_names_expr":[
                    "hand2_joint_link_1_1",
                    "hand2_joint_link_2_1",
                    "hand2_joint_link_3_1",
                    "hand2_joint_link_4_1",
                    "hand2_joint_link_5_1",
                    "hand2_joint_link_1_2",
                    "hand2_joint_link_2_2",
                    "hand2_joint_link_3_2",
                    "hand2_joint_link_4_2",
                    "hand2_joint_link_5_2",
                    "hand2_joint_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            }
        },
        "amplitude_scale":1.0,
        "period":10.0,
        "sim_time":20.0,
        "mimic_joints":[
            "hand1_joint_link_2_2",
            "hand1_joint_link_3_2",
            "hand1_joint_link_4_2",
            "hand1_joint_link_5_2",
            "hand1_joint_link_1_3",
            "hand2_joint_link_2_2",
            "hand2_joint_link_3_2",
            "hand2_joint_link_4_2",
            "hand2_joint_link_5_2",
            "hand2_joint_link_1_3",
        ]
    },
    # Psi-DC-02
    "Psi-DC-02":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_Psi_DC_02/PsiRobot_DC_02.usd",
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                "arm1_joint_link1": 0.0,
                "arm1_joint_link2": 0.0,
                "arm1_joint_link3": 0.0,
                "arm1_joint_link4": 0.0,
                "arm1_joint_link5": 0.0,
                "arm1_joint_link6": 0.0,
                "arm1_joint_link7": 0.0,
                "arm2_joint_link1": 0.0,
                "arm2_joint_link2": 0.0,
                "arm2_joint_link3": 0.0,
                "arm2_joint_link4": 0.0,
                "arm2_joint_link5": 0.0,
                "arm2_joint_link6": 0.0,
                "arm2_joint_link7": 0.0,
                "hand1_joint_link_1_1":0.0,
                "hand1_joint_link_1_2":0.63,
                "hand1_joint_link_1_3":0.03,
                "hand1_joint_link_2_1":3.10,
                "hand1_joint_link_2_2":1.56,
                "hand1_joint_link_3_1":3.06,
                "hand1_joint_link_3_2":1.56,
                "hand1_joint_link_4_1":3.06,
                "hand1_joint_link_4_2":1.56,
                "hand1_joint_link_5_1":3.04,
                "hand1_joint_link_5_2":1.56,
                "hand2_joint_link_1_1":0.0,
                "hand2_joint_link_1_2":0.64,
                "hand2_joint_link_1_3":0.03,
                "hand2_joint_link_2_1":3.11,
                "hand2_joint_link_2_2":1.56,
                "hand2_joint_link_3_1":3.06,
                "hand2_joint_link_3_2":1.56,
                "hand2_joint_link_4_1":3.08,
                "hand2_joint_link_4_2":1.56,
                "hand2_joint_link_5_1":3.05,
                "hand2_joint_link_5_2":1.56,
            }
        },
        "actuators":{
            "arm1":{
                "joint_names_expr":[
                    "arm1_joint_link1",
                    "arm1_joint_link2",
                    "arm1_joint_link3",
                    "arm1_joint_link4",
                    "arm1_joint_link5",
                    "arm1_joint_link6",
                    "arm1_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm2":{
                "joint_names_expr":[
                    "arm2_joint_link1",
                    "arm2_joint_link2",
                    "arm2_joint_link3",
                    "arm2_joint_link4",
                    "arm2_joint_link5",
                    "arm2_joint_link6",
                    "arm2_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand1":{
                "joint_names_expr":[
                    "hand1_joint_link_1_1",
                    "hand1_joint_link_2_1",
                    "hand1_joint_link_3_1",
                    "hand1_joint_link_4_1",
                    "hand1_joint_link_5_1",
                    "hand1_joint_link_1_2",
                    "hand1_joint_link_2_2",
                    "hand1_joint_link_3_2",
                    "hand1_joint_link_4_2",
                    "hand1_joint_link_5_2",
                    "hand1_joint_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand2":{
                "joint_names_expr":[
                    "hand2_joint_link_1_1",
                    "hand2_joint_link_2_1",
                    "hand2_joint_link_3_1",
                    "hand2_joint_link_4_1",
                    "hand2_joint_link_5_1",
                    "hand2_joint_link_1_2",
                    "hand2_joint_link_2_2",
                    "hand2_joint_link_3_2",
                    "hand2_joint_link_4_2",
                    "hand2_joint_link_5_2",
                    "hand2_joint_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            }
        },
        "amplitude_scale":1.0,
        "period":10.0,
        "sim_time":20.0,
        "mimic_joints":[
            "hand1_joint_link_2_2",
            "hand1_joint_link_3_2",
            "hand1_joint_link_4_2",
            "hand1_joint_link_5_2",
            "hand1_joint_link_1_3",
            "hand2_joint_link_2_2",
            "hand2_joint_link_3_2",
            "hand2_joint_link_4_2",
            "hand2_joint_link_5_2",
            "hand2_joint_link_1_3",
        ]
    },
    "Psi-DC-02-D435":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_Psi_DC_02/PsiRobot_DC_02_D435.usd",
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                "arm1_joint_link1": 0.0,
                "arm1_joint_link2": 0.0,
                "arm1_joint_link3": 0.0,
                "arm1_joint_link4": 0.0,
                "arm1_joint_link5": 0.0,
                "arm1_joint_link6": 0.0,
                "arm1_joint_link7": 0.0,
                "arm2_joint_link1": 0.0,
                "arm2_joint_link2": 0.0,
                "arm2_joint_link3": 0.0,
                "arm2_joint_link4": 0.0,
                "arm2_joint_link5": 0.0,
                "arm2_joint_link6": 0.0,
                "arm2_joint_link7": 0.0,
                "hand1_joint_link_1_1":0.0,
                "hand1_joint_link_1_2":0.63,
                "hand1_joint_link_1_3":0.03,
                "hand1_joint_link_2_1":3.10,
                "hand1_joint_link_2_2":1.56,
                "hand1_joint_link_3_1":3.06,
                "hand1_joint_link_3_2":1.56,
                "hand1_joint_link_4_1":3.06,
                "hand1_joint_link_4_2":1.56,
                "hand1_joint_link_5_1":3.04,
                "hand1_joint_link_5_2":1.56,
                "hand2_joint_link_1_1":0.0,
                "hand2_joint_link_1_2":0.64,
                "hand2_joint_link_1_3":0.03,
                "hand2_joint_link_2_1":3.11,
                "hand2_joint_link_2_2":1.56,
                "hand2_joint_link_3_1":3.06,
                "hand2_joint_link_3_2":1.56,
                "hand2_joint_link_4_1":3.08,
                "hand2_joint_link_4_2":1.56,
                "hand2_joint_link_5_1":3.05,
                "hand2_joint_link_5_2":1.56,
            }
        },
        "actuators":{
            "arm1":{
                "joint_names_expr":[
                    "arm1_joint_link1",
                    "arm1_joint_link2",
                    "arm1_joint_link3",
                    "arm1_joint_link4",
                    "arm1_joint_link5",
                    "arm1_joint_link6",
                    "arm1_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm2":{
                "joint_names_expr":[
                    "arm2_joint_link1",
                    "arm2_joint_link2",
                    "arm2_joint_link3",
                    "arm2_joint_link4",
                    "arm2_joint_link5",
                    "arm2_joint_link6",
                    "arm2_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand1":{
                "joint_names_expr":[
                    "hand1_joint_link_1_1",
                    "hand1_joint_link_2_1",
                    "hand1_joint_link_3_1",
                    "hand1_joint_link_4_1",
                    "hand1_joint_link_5_1",
                    "hand1_joint_link_1_2",
                    "hand1_joint_link_2_2",
                    "hand1_joint_link_3_2",
                    "hand1_joint_link_4_2",
                    "hand1_joint_link_5_2",
                    "hand1_joint_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand2":{
                "joint_names_expr":[
                    "hand2_joint_link_1_1",
                    "hand2_joint_link_2_1",
                    "hand2_joint_link_3_1",
                    "hand2_joint_link_4_1",
                    "hand2_joint_link_5_1",
                    "hand2_joint_link_1_2",
                    "hand2_joint_link_2_2",
                    "hand2_joint_link_3_2",
                    "hand2_joint_link_4_2",
                    "hand2_joint_link_5_2",
                    "hand2_joint_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            }
        },
        "amplitude_scale":1.0,
        "period":10.0,
        "sim_time":20.0,
        "mimic_joints":[
            "hand1_joint_link_2_2",
            "hand1_joint_link_3_2",
            "hand1_joint_link_4_2",
            "hand1_joint_link_5_2",
            "hand1_joint_link_1_3",
            "hand2_joint_link_2_2",
            "hand2_joint_link_3_2",
            "hand2_joint_link_4_2",
            "hand2_joint_link_5_2",
            "hand2_joint_link_1_3",
        ]
    },
    "Psi-DC-02-RuiYan":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_Psi_DC_02/PsiRobot_DC_02_RuiYan.usd",
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                "arm1_joint_link1": 0.0,
                "arm1_joint_link2": 0.0,
                "arm1_joint_link3": 0.0,
                "arm1_joint_link4": 0.0,
                "arm1_joint_link5": 0.0,
                "arm1_joint_link6": 0.0,
                "arm1_joint_link7": 0.0,
                "arm2_joint_link1": 0.0,
                "arm2_joint_link2": 0.0,
                "arm2_joint_link3": 0.0,
                "arm2_joint_link4": 0.0,
                "arm2_joint_link5": 0.0,
                "arm2_joint_link6": 0.0,
                "arm2_joint_link7": 0.0,
                "hand1_joint_link_1_1":0.0,
                "hand1_joint_link_1_2":0.63,
                "hand1_joint_link_1_3":0.03,
                "hand1_joint_link_2_1":3.10,
                "hand1_joint_link_2_2":1.56,
                "hand1_joint_link_3_1":3.06,
                "hand1_joint_link_3_2":1.56,
                "hand1_joint_link_4_1":3.06,
                "hand1_joint_link_4_2":1.56,
                "hand1_joint_link_5_1":3.04,
                "hand1_joint_link_5_2":1.56,
                "hand2_joint_link_1_1":0.0,
                "hand2_joint_link_1_2":0.64,
                "hand2_joint_link_1_3":0.03,
                "hand2_joint_link_2_1":3.11,
                "hand2_joint_link_2_2":1.56,
                "hand2_joint_link_3_1":3.06,
                "hand2_joint_link_3_2":1.56,
                "hand2_joint_link_4_1":3.08,
                "hand2_joint_link_4_2":1.56,
                "hand2_joint_link_5_1":3.05,
                "hand2_joint_link_5_2":1.56,
            }
        },
        "actuators":{
            "arm1":{
                "joint_names_expr":[
                    "arm1_joint_link1",
                    "arm1_joint_link2",
                    "arm1_joint_link3",
                    "arm1_joint_link4",
                    "arm1_joint_link5",
                    "arm1_joint_link6",
                    "arm1_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm2":{
                "joint_names_expr":[
                    "arm2_joint_link1",
                    "arm2_joint_link2",
                    "arm2_joint_link3",
                    "arm2_joint_link4",
                    "arm2_joint_link5",
                    "arm2_joint_link6",
                    "arm2_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand1":{
                "joint_names_expr":[
                    "hand1_joint_link_1_1",
                    "hand1_joint_link_2_1",
                    "hand1_joint_link_3_1",
                    "hand1_joint_link_4_1",
                    "hand1_joint_link_5_1",
                    "hand1_joint_link_1_2",
                    "hand1_joint_link_2_2",
                    "hand1_joint_link_3_2",
                    "hand1_joint_link_4_2",
                    "hand1_joint_link_5_2",
                    "hand1_joint_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand2":{
                "joint_names_expr":[
                    "hand2_joint_link_1_1",
                    "hand2_joint_link_2_1",
                    "hand2_joint_link_3_1",
                    "hand2_joint_link_4_1",
                    "hand2_joint_link_5_1",
                    "hand2_joint_link_1_2",
                    "hand2_joint_link_2_2",
                    "hand2_joint_link_3_2",
                    "hand2_joint_link_4_2",
                    "hand2_joint_link_5_2",
                    "hand2_joint_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            }
        },
        "amplitude_scale":1.0,
        "period":10.0,
        "sim_time":20.0,
        "mimic_joints":[
            "hand1_joint_link_2_2",
            "hand1_joint_link_3_2",
            "hand1_joint_link_4_2",
            "hand1_joint_link_5_2",
            "hand1_joint_link_1_3",
            "hand2_joint_link_2_2",
            "hand2_joint_link_3_2",
            "hand2_joint_link_4_2",
            "hand2_joint_link_5_2",
            "hand2_joint_link_1_3",
        ]
    },
    "Psi-DC-02-PsiSynHand":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_Psi_DC_02/PsiRobot_DC_02_PsiSynHand.usd",
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                "arm1_joint_link1": 0.0,
                "arm1_joint_link2": 0.0,
                "arm1_joint_link3": 0.0,
                "arm1_joint_link4": 0.0,
                "arm1_joint_link5": 0.0,
                "arm1_joint_link6": 0.0,
                "arm1_joint_link7": 0.0,
                "arm2_joint_link1": 0.0,
                "arm2_joint_link2": 0.0,
                "arm2_joint_link3": 0.0,
                "arm2_joint_link4": 0.0,
                "arm2_joint_link5": 0.0,
                "arm2_joint_link6": 0.0,
                "arm2_joint_link7": 0.0,
                "hand1_joint_link_1_1":0.0,
                "hand1_joint_link_1_2":0.0,
                "hand1_joint_link_1_3":0.0,
                "hand1_joint_link_1_4":0.0,
                "hand1_joint_link_1_5":0.0,
                "hand1_joint_link_2_1":0.0,
                "hand1_joint_link_2_2":0.0,
                "hand1_joint_link_2_3":0.0,
                "hand1_joint_link_2_4":0.0,
                "hand1_joint_link_3_1":0.0,
                "hand1_joint_link_3_2":0.0,
                "hand1_joint_link_3_3":0.0,
                "hand1_joint_link_3_4":0.0,
                "hand1_joint_link_4_1":0.0,
                "hand1_joint_link_4_2":0.0,
                "hand1_joint_link_4_3":0.0,
                "hand1_joint_link_4_4":0.0,
                "hand1_joint_link_5_1":0.0,
                "hand1_joint_link_5_2":0.0,
                "hand1_joint_link_5_3":0.0,
                "hand1_joint_link_5_4":0.0,
                "hand2_joint_link_1_1":0.0,
                "hand2_joint_link_1_2":0.0,
                "hand2_joint_link_1_3":0.0,
                "hand2_joint_link_1_4":0.0,
                "hand2_joint_link_1_5":0.0,
                "hand2_joint_link_2_1":0.0,
                "hand2_joint_link_2_2":0.0,
                "hand2_joint_link_2_3":0.0,
                "hand2_joint_link_2_4":0.0,
                "hand2_joint_link_3_1":0.0,
                "hand2_joint_link_3_2":0.0,
                "hand2_joint_link_3_3":0.0,
                "hand2_joint_link_3_4":0.0,
                "hand2_joint_link_4_1":0.0,
                "hand2_joint_link_4_2":0.0,
                "hand2_joint_link_4_3":0.0,
                "hand2_joint_link_4_4":0.0,
                "hand2_joint_link_5_1":0.0,
                "hand2_joint_link_5_2":0.0,
                "hand2_joint_link_5_3":0.0,
                "hand2_joint_link_5_4":0.0,
                
            }
        },
        "actuators":{
            "arm1":{
                "joint_names_expr":[
                    "arm1_joint_link1",
                    "arm1_joint_link2",
                    "arm1_joint_link3",
                    "arm1_joint_link4",
                    "arm1_joint_link5",
                    "arm1_joint_link6",
                    "arm1_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm2":{
                "joint_names_expr":[
                    "arm2_joint_link1",
                    "arm2_joint_link2",
                    "arm2_joint_link3",
                    "arm2_joint_link4",
                    "arm2_joint_link5",
                    "arm2_joint_link6",
                    "arm2_joint_link7",
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand1":{
                "joint_names_expr":[
                    "hand1_joint_link_1_1",
                    "hand1_joint_link_2_1",
                    "hand1_joint_link_3_1",
                    "hand1_joint_link_4_1",
                    "hand1_joint_link_5_1",
                    "hand1_joint_link_1_2",
                    "hand1_joint_link_2_2",
                    "hand1_joint_link_3_2",
                    "hand1_joint_link_4_2",
                    "hand1_joint_link_5_2",
                    "hand1_joint_link_1_3",
                    "hand1_joint_link_2_3",
                    "hand1_joint_link_3_3",
                    "hand1_joint_link_4_3",
                    "hand1_joint_link_5_3",
                    "hand1_joint_link_1_4",
                    "hand1_joint_link_2_4",
                    "hand1_joint_link_3_4",
                    "hand1_joint_link_4_4",
                    "hand1_joint_link_5_4",
                    "hand1_joint_link_1_5",
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand2":{
                "joint_names_expr":[
                    "hand2_joint_link_1_1",
                    "hand2_joint_link_2_1",
                    "hand2_joint_link_3_1",
                    "hand2_joint_link_4_1",
                    "hand2_joint_link_5_1",
                    "hand2_joint_link_1_2",
                    "hand2_joint_link_2_2",
                    "hand2_joint_link_3_2",
                    "hand2_joint_link_4_2",
                    "hand2_joint_link_5_2",
                    "hand2_joint_link_1_3",
                    "hand2_joint_link_2_3",
                    "hand2_joint_link_3_3",
                    "hand2_joint_link_4_3",
                    "hand2_joint_link_5_3",
                    "hand2_joint_link_1_4",
                    "hand2_joint_link_2_4",
                    "hand2_joint_link_3_4",
                    "hand2_joint_link_4_4",
                    "hand2_joint_link_5_4",
                    "hand2_joint_link_1_5",
                ],
                "stiffness":None,
                "damping":None,
            }
        },
        "amplitude_scale":1.0,
        "period":5.0,
        "sim_time":5.0,
        "mimic_joints":[
            "hand1_joint_link_2_4",
            "hand1_joint_link_3_4",
            "hand1_joint_link_4_4",
            "hand1_joint_link_5_4",
            "hand1_joint_link_1_5",
            "hand2_joint_link_2_4",
            "hand2_joint_link_3_4",
            "hand2_joint_link_4_4",
            "hand2_joint_link_5_4",
            "hand2_joint_link_1_5",
        ]
    },
    # A2D
    "A2D-NoHand":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_A2D/A2D_NoHand.usd",
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                # 
                "joint_waist_link":0.0,
                "joint_body_link":0.0,
                #
                "joint_head_link_1":0.0,
                "joint_head_link_2":0.0,
                #
                "joint_wheel_link_1":0.0,
                "joint_wheel_link_2":0.0,
                # arm1
                "joint_arm1_link_1": 0.0,
                "joint_arm1_link_2": 0.0,
                "joint_arm1_link_3": 0.0,
                "joint_arm1_link_4": 0.0,
                "joint_arm1_link_5": 0.0,
                "joint_arm1_link_6": 0.0,
                "joint_arm1_link_7": 0.0,
                # arm2
                "joint_arm2_link_1": 0.0,
                "joint_arm2_link_2": 0.0,
                "joint_arm2_link_3": 0.0,
                "joint_arm2_link_4": 0.0,
                "joint_arm2_link_5": 0.0,
                "joint_arm2_link_6": 0.0,
                "joint_arm2_link_7": 0.0,
            }
        },
        "actuators":{
            "body":{
                "joint_names_expr":[
                    "joint_waist_link",
                    "joint_body_link",
                ],
                "stiffness":None,
                "damping":None,
            },
            "head":{
                "joint_names_expr":[
                    "joint_head_link_1",
                    "joint_head_link_2"
                ],
                "stiffness":None,
                "damping":None,
            },
            "wheel":{
                "joint_names_expr":[
                    "joint_wheel_link_1",
                    "joint_wheel_link_2"
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm1":{
                "joint_names_expr":[
                    "joint_arm1_link_1",
                    "joint_arm1_link_2",
                    "joint_arm1_link_3",
                    "joint_arm1_link_4",
                    "joint_arm1_link_5",
                    "joint_arm1_link_6",
                    "joint_arm1_link_7"
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm2":{
                "joint_names_expr":[
                    "joint_arm2_link_1",
                    "joint_arm2_link_2",
                    "joint_arm2_link_3",
                    "joint_arm2_link_4",
                    "joint_arm2_link_5",
                    "joint_arm2_link_6",
                    "joint_arm2_link_7"
                ],
                "stiffness":None,
                "damping":None,
            },
        },
        "amplitude_scale":1.0,
        "period":10.0,
        "sim_time":20.0,
        "excluded_joints":[
            "joint_wheel_link_1",
            "joint_wheel_link_2",    
        ],
        "excluded_actuators":[
            "wheel",
        ],
    },
    "A2D-RuiYan":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_A2D/A2D_RuiYan.usd",
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                # 
                "joint_waist_link":0.0,
                "joint_body_link":0.0,
                #
                "joint_head_link_1":0.0,
                "joint_head_link_2":0.0,
                #
                "joint_wheel_link_1":0.0,
                "joint_wheel_link_2":0.0,
                # arm1
                "joint_arm1_link_1": 0.0,
                "joint_arm1_link_2": 0.0,
                "joint_arm1_link_3": 0.0,
                "joint_arm1_link_4": 0.0,
                "joint_arm1_link_5": 0.0,
                "joint_arm1_link_6": 0.0,
                "joint_arm1_link_7": 0.0,
                # arm2
                "joint_arm2_link_1": 0.0,
                "joint_arm2_link_2": 0.0,
                "joint_arm2_link_3": 0.0,
                "joint_arm2_link_4": 0.0,
                "joint_arm2_link_5": 0.0,
                "joint_arm2_link_6": 0.0,
                "joint_arm2_link_7": 0.0,
                # hand1
                "joint_hand1_link_1_1": 0.0,
                "joint_hand1_link_1_2": 0.0,
                "joint_hand1_link_1_3": 0.0,
                "joint_hand1_link_2_1": 0.0,
                "joint_hand1_link_2_2": 0.0,
                "joint_hand1_link_3_1": 0.0,
                "joint_hand1_link_3_2": 0.0,
                "joint_hand1_link_4_1": 0.0,
                "joint_hand1_link_4_2": 0.0,
                "joint_hand1_link_5_1": 0.0,
                "joint_hand1_link_5_2": 0.0,
                # hand2 
                "joint_hand2_link_1_1": 0.0,
                "joint_hand2_link_1_2": 0.0,
                "joint_hand2_link_1_3": 0.0,
                "joint_hand2_link_2_1": 0.0,
                "joint_hand2_link_2_2": 0.0,
                "joint_hand2_link_3_1": 0.0,
                "joint_hand2_link_3_2": 0.0,
                "joint_hand2_link_4_1": 0.0,
                "joint_hand2_link_4_2": 0.0,
                "joint_hand2_link_5_1": 0.0,
                "joint_hand2_link_5_2": 0.0,
            }
        },
        "actuators":{
            "body":{
                "joint_names_expr":[
                    "joint_waist_link",
                    "joint_body_link",
                ],
                "stiffness":None,
                "damping":None,
            },
            "head":{
                "joint_names_expr":[
                    "joint_head_link_1",
                    "joint_head_link_2"
                ],
                "stiffness":None,
                "damping":None,
            },
            "wheel":{
                "joint_names_expr":[
                    "joint_wheel_link_1",
                    "joint_wheel_link_2"
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm1":{
                "joint_names_expr":[
                    "joint_arm1_link_1",
                    "joint_arm1_link_2",
                    "joint_arm1_link_3",
                    "joint_arm1_link_4",
                    "joint_arm1_link_5",
                    "joint_arm1_link_6",
                    "joint_arm1_link_7"
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm2":{
                "joint_names_expr":[
                    "joint_arm2_link_1",
                    "joint_arm2_link_2",
                    "joint_arm2_link_3",
                    "joint_arm2_link_4",
                    "joint_arm2_link_5",
                    "joint_arm2_link_6",
                    "joint_arm2_link_7"
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand1":{
                "joint_names_expr":[
                    "joint_hand1_link_1_1",
                    "joint_hand1_link_2_1",
                    "joint_hand1_link_3_1",
                    "joint_hand1_link_4_1",
                    "joint_hand1_link_5_1",
                    "joint_hand1_link_1_2",
                    "joint_hand1_link_2_2",
                    "joint_hand1_link_3_2",
                    "joint_hand1_link_4_2",
                    "joint_hand1_link_5_2",
                    "joint_hand1_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand2":{
                "joint_names_expr":[
                    "joint_hand2_link_1_1",
                    "joint_hand2_link_2_1",
                    "joint_hand2_link_3_1",
                    "joint_hand2_link_4_1",
                    "joint_hand2_link_5_1",
                    "joint_hand2_link_1_2",
                    "joint_hand2_link_2_2",
                    "joint_hand2_link_3_2",
                    "joint_hand2_link_4_2",
                    "joint_hand2_link_5_2",
                    "joint_hand2_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            }
        },
        "amplitude_scale":1.0,
        "period":10.0,
        "sim_time":20.0,
        "mimic_joints":[
            "joint_hand1_link_2_2",
            "joint_hand1_link_3_2",
            "joint_hand1_link_4_2",
            "joint_hand1_link_5_2",
            "joint_hand1_link_1_3",
            "joint_hand2_link_2_2",
            "joint_hand2_link_3_2",
            "joint_hand2_link_4_2",
            "joint_hand2_link_5_2",
            "joint_hand2_link_1_3",
        ],
        "excluded_joints":[
            "joint_wheel_link_1",
            "joint_wheel_link_2",    
        ],
        "excluded_actuators":[
            "wheel",
        ],
    },
    "A2D-RuiYan-D405":{
        "prim_path": "/World/envs/env_[0-9]+/Robot",
        "spawn":{
            "usd_path":PSILAB_USD_ASSET_DIR+"/robots/Robot_A2D/A2D_RuiYan_D405.usd",
        },
        "init_state":{
            "pos":(0.0, 0.0, 0.0),
            "rot":(1.0,0.0,0.0,0.0),
            "joint_pos":{
                # 
                "joint_waist_link":0.0,
                "joint_body_link":0.0,
                #
                "joint_head_link_1":0.0,
                "joint_head_link_2":0.0,
                #
                "joint_wheel_link_1":0.0,
                "joint_wheel_link_2":0.0,
                # arm1
                "joint_arm1_link_1": 0.0,
                "joint_arm1_link_2": 0.0,
                "joint_arm1_link_3": 0.0,
                "joint_arm1_link_4": 0.0,
                "joint_arm1_link_5": 0.0,
                "joint_arm1_link_6": 0.0,
                "joint_arm1_link_7": 0.0,
                # arm2
                "joint_arm2_link_1": 0.0,
                "joint_arm2_link_2": 0.0,
                "joint_arm2_link_3": 0.0,
                "joint_arm2_link_4": 0.0,
                "joint_arm2_link_5": 0.0,
                "joint_arm2_link_6": 0.0,
                "joint_arm2_link_7": 0.0,
                # hand1
                "joint_hand1_link_1_1": 0.0,
                "joint_hand1_link_1_2": 0.0,
                "joint_hand1_link_1_3": 0.0,
                "joint_hand1_link_2_1": 0.0,
                "joint_hand1_link_2_2": 0.0,
                "joint_hand1_link_3_1": 0.0,
                "joint_hand1_link_3_2": 0.0,
                "joint_hand1_link_4_1": 0.0,
                "joint_hand1_link_4_2": 0.0,
                "joint_hand1_link_5_1": 0.0,
                "joint_hand1_link_5_2": 0.0,
                # hand2 
                "joint_hand2_link_1_1": 0.0,
                "joint_hand2_link_1_2": 0.0,
                "joint_hand2_link_1_3": 0.0,
                "joint_hand2_link_2_1": 0.0,
                "joint_hand2_link_2_2": 0.0,
                "joint_hand2_link_3_1": 0.0,
                "joint_hand2_link_3_2": 0.0,
                "joint_hand2_link_4_1": 0.0,
                "joint_hand2_link_4_2": 0.0,
                "joint_hand2_link_5_1": 0.0,
                "joint_hand2_link_5_2": 0.0,
            }
        },
        "actuators":{
            "body":{
                "joint_names_expr":[
                    "joint_waist_link",
                    "joint_body_link",
                ],
                "stiffness":None,
                "damping":None,
            },
            "head":{
                "joint_names_expr":[
                    "joint_head_link_1",
                    "joint_head_link_2"
                ],
                "stiffness":None,
                "damping":None,
            },
            "wheel":{
                "joint_names_expr":[
                    "joint_wheel_link_1",
                    "joint_wheel_link_2"
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm1":{
                "joint_names_expr":[
                    "joint_arm1_link_1",
                    "joint_arm1_link_2",
                    "joint_arm1_link_3",
                    "joint_arm1_link_4",
                    "joint_arm1_link_5",
                    "joint_arm1_link_6",
                    "joint_arm1_link_7"
                ],
                "stiffness":None,
                "damping":None,
            },
            "arm2":{
                "joint_names_expr":[
                    "joint_arm2_link_1",
                    "joint_arm2_link_2",
                    "joint_arm2_link_3",
                    "joint_arm2_link_4",
                    "joint_arm2_link_5",
                    "joint_arm2_link_6",
                    "joint_arm2_link_7"
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand1":{
                "joint_names_expr":[
                    "joint_hand1_link_1_1",
                    "joint_hand1_link_2_1",
                    "joint_hand1_link_3_1",
                    "joint_hand1_link_4_1",
                    "joint_hand1_link_5_1",
                    "joint_hand1_link_1_2",
                    "joint_hand1_link_2_2",
                    "joint_hand1_link_3_2",
                    "joint_hand1_link_4_2",
                    "joint_hand1_link_5_2",
                    "joint_hand1_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            },
            "hand2":{
                "joint_names_expr":[
                    "joint_hand2_link_1_1",
                    "joint_hand2_link_2_1",
                    "joint_hand2_link_3_1",
                    "joint_hand2_link_4_1",
                    "joint_hand2_link_5_1",
                    "joint_hand2_link_1_2",
                    "joint_hand2_link_2_2",
                    "joint_hand2_link_3_2",
                    "joint_hand2_link_4_2",
                    "joint_hand2_link_5_2",
                    "joint_hand2_link_1_3"
                ],
                "stiffness":None,
                "damping":None,
            }
        },
        "amplitude_scale":1.0,
        "period":10.0,
        "sim_time":20.0,
        "mimic_joints":[
            "joint_hand1_link_2_2",
            "joint_hand1_link_3_2",
            "joint_hand1_link_4_2",
            "joint_hand1_link_5_2",
            "joint_hand1_link_1_3",
            "joint_hand2_link_2_2",
            "joint_hand2_link_3_2",
            "joint_hand2_link_4_2",
            "joint_hand2_link_5_2",
            "joint_hand2_link_1_3",
        ],
        "excluded_joints":[
            "joint_wheel_link_1",
            "joint_wheel_link_2",    
        ],
        "excluded_actuators":[
            "wheel",
        ],
    },
}
